-- CreateTable
CREATE TABLE "PRACTICE_PROGRESS" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER NOT NULL,
    "solvedIds" INTEGER[],
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PRACTICE_PROGRESS_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "PRACTICE_PROGRESS_userId_key" ON "PRACTICE_PROGRESS"("userId");

-- AddForeignKey
ALTER TABLE "PRACTICE_PROGRESS" ADD CONSTRAINT "PRACTICE_PROGRESS_userId_fkey" FOREIGN KEY ("userId") REFERENCES "USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
