-- CreateTable
CREATE TABLE "TAG" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TAG_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SENTENCE_TAG" (
    "id" SERIAL NOT NULL,
    "sentenceId" INTEGER NOT NULL,
    "tagId" INTEGER NOT NULL,

    CONSTRAINT "SENTENCE_TAG_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "TAG_name_key" ON "TAG"("name");

-- CreateIndex
CREATE UNIQUE INDEX "SENTENCE_TAG_sentenceId_tagId_key" ON "SENTENCE_TAG"("sentenceId", "tagId");

-- AddForeignKey
ALTER TABLE "SENTENCE_TAG" ADD CONSTRAINT "SENTENCE_TAG_sentenceId_fkey" FOREIGN KEY ("sentenceId") REFERENCES "SENTENCE"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SENTENCE_TAG" ADD CONSTRAINT "SENTENCE_TAG_tagId_fkey" FOREIGN KEY ("tagId") REFERENCES "TAG"("id") ON DELETE CASCADE ON UPDATE CASCADE;
