-- DropForeignKey
ALTER TABLE "WORD" DROP CONSTRAINT "WORD_sentenceId_fkey";

-- AddForeignKey
ALTER TABLE "WORD" ADD CONSTRAINT "WORD_sentenceId_fkey" FOREIGN KEY ("sentenceId") REFERENCES "SENTENCE"("id") ON DELETE CASCADE ON UPDATE CASCADE;
