-- CreateTable
CREATE TABLE "STUDY_LOG" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER NOT NULL,
    "date" DATE NOT NULL,
    "count" INTEGER NOT NULL DEFAULT 1,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "STUDY_LOG_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "STUDY_LOG_userId_date_key" ON "STUDY_LOG"("userId", "date");

-- AddForeignKey
ALTER TABLE "STUDY_LOG" ADD CONSTRAINT "STUDY_LOG_userId_fkey" FOREIGN KEY ("userId") REFERENCES "USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
