-- CreateTable
CREATE TABLE "EXPRESSION_FAVORITE" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER NOT NULL,
    "expressionId" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "EXPRESSION_FAVORITE_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "EXPRESSION_FAVORITE_userId_expressionId_key" ON "EXPRESSION_FAVORITE"("userId", "expressionId");

-- AddForeignKey
ALTER TABLE "EXPRESSION_FAVORITE" ADD CONSTRAINT "EXPRESSION_FAVORITE_userId_fkey" FOREIGN KEY ("userId") REFERENCES "USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EXPRESSION_FAVORITE" ADD CONSTRAINT "EXPRESSION_FAVORITE_expressionId_fkey" FOREIGN KEY ("expressionId") REFERENCES "EXPRESSION"("id") ON DELETE CASCADE ON UPDATE CASCADE;
