-- CreateTable
CREATE TABLE "EXPRESSION" (
    "id" SERIAL NOT NULL,
    "content" TEXT NOT NULL,
    "meaning" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "EXPRESSION_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EXPRESSION_SENTENCE" (
    "id" SERIAL NOT NULL,
    "expressionId" INTEGER NOT NULL,
    "sentenceId" INTEGER NOT NULL,

    CONSTRAINT "EXPRESSION_SENTENCE_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "EXPRESSION_content_key" ON "EXPRESSION"("content");

-- CreateIndex
CREATE UNIQUE INDEX "EXPRESSION_SENTENCE_expressionId_sentenceId_key" ON "EXPRESSION_SENTENCE"("expressionId", "sentenceId");

-- AddForeignKey
ALTER TABLE "EXPRESSION_SENTENCE" ADD CONSTRAINT "EXPRESSION_SENTENCE_expressionId_fkey" FOREIGN KEY ("expressionId") REFERENCES "EXPRESSION"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EXPRESSION_SENTENCE" ADD CONSTRAINT "EXPRESSION_SENTENCE_sentenceId_fkey" FOREIGN KEY ("sentenceId") REFERENCES "SENTENCE"("id") ON DELETE CASCADE ON UPDATE CASCADE;
