-- CreateTable
CREATE TABLE "SENTENCE_PRACTICE" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER NOT NULL,
    "sentenceId" INTEGER NOT NULL,
    "correctCount" INTEGER NOT NULL DEFAULT 0,
    "lastPracticedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SENTENCE_PRACTICE_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "SENTENCE_PRACTICE_userId_sentenceId_key" ON "SENTENCE_PRACTICE"("userId", "sentenceId");

-- AddForeignKey
ALTER TABLE "SENTENCE_PRACTICE" ADD CONSTRAINT "SENTENCE_PRACTICE_userId_fkey" FOREIGN KEY ("userId") REFERENCES "USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SENTENCE_PRACTICE" ADD CONSTRAINT "SENTENCE_PRACTICE_sentenceId_fkey" FOREIGN KEY ("sentenceId") REFERENCES "SENTENCE"("id") ON DELETE CASCADE ON UPDATE CASCADE;
