-- CreateTable
CREATE TABLE "FREE_WRITING" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER NOT NULL,
    "korean" TEXT NOT NULL,
    "english" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FREE_WRITING_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "FREE_WRITING" ADD CONSTRAINT "FREE_WRITING_userId_fkey" FOREIGN KEY ("userId") REFERENCES "USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
